### ISSUE TITLE
Cannot access uninitialized variable.

### ISSUE THREAD

**Issue by brianorwhatever** [bun-community/sveltekit-adapter-bun#1]
Some of my dependencies when running the production build blow up when they try to access the dependency. It throws a ReferenceError "Cannot access uninitialized variable." that isn't very helpful and is hard to debug. I tried messing with the vite [`optimizeDep`](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-exclude) and [`ssr`](https://vitejs.dev/config/ssr-options.html#ssr-external) options but no luck. I have disabled bun for now and it works but would like to get bun enabled again ASAP!

minimal repro add this to a +server.ts page
```
import { hash } from '@stablelib/sha256';
console.log(hash);
```

however this is just segfaulting not even throwing that error

**Comment by Kapsonfire** [comment]
The segfault is bun related, not the adapter. I passed this to the oven org

**Comment by Kapsonfire** [comment]
Can you try to use the canary version and check if its working?

`bun upgrade --canary`

**Comment by brianorwhatever** [comment]
So it looks like that fixed the sha256 library however my own library has the same exact issue.. not sure how to proceed in fixing my library. Also probably unrelated but everytime I first boot up my svelte server the first request always fails with a 500 and only logs `undefined`. Is that a known issue? If not I will open it as a new issue since I think it's unrelated to this uninitialized variable problem. As far as the original issue goes I guess this isn't the best place for it maybe I will open something up on the bun repo

**Comment by Kapsonfire** [comment]
can you check up with latest canary?
