### ISSUE TITLE
More recent adapter

### ISSUE THREAD

**Issue by veneficium42** [bun-community/sveltekit-adapter-bun#6]
There seems to be a more recently updated adapter for Svetle-kit made for Bun, which one should be used?

[https://github.com/gornostay25/svelte-adapter-bun](url)

**Comment by gornostay25** [comment]
@FedFer98123 bun-community/sveltekit-adapter-bun is an old fork of [gornostay25/svelte-adapter-bun](https://github.com/gornostay25/svelte-adapter-bun)
